"use client";
import {useState} from "react";
import {useLocale,useTranslations} from "next-intl";
import {useRouter} from "next/navigation";
import {BookOpen,Languages,LoaderCircle} from "lucide-react";
import {useAuth} from "@/components/providers";

export default function LoginPage(){
  const t=useTranslations("Auth");const locale=useLocale();const router=useRouter();const {login,register}=useAuth();
  const [mode,setMode]=useState<"login"|"register">("login");const [pending,setPending]=useState(false);const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");const data=new FormData(event.currentTarget);try{if(mode==="login")await login(String(data.get("email")),String(data.get("password")));else await register(String(data.get("name")),String(data.get("email")),String(data.get("password")));router.replace(`/${locale}`);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to sign in");}finally{setPending(false);}}
  return <main className="min-h-screen grid lg:grid-cols-[1.1fr_.9fr]">
    <section className="hidden lg:flex p-14 bg-[var(--forest)] text-white flex-col justify-between relative overflow-hidden"><div className="absolute w-80 h-80 rounded-full bg-[var(--lime)]/20 -right-28 top-16"/><div className="flex items-center gap-3 text-xl font-black"><span className="w-11 h-11 bg-[var(--lime)] text-[var(--forest)] rounded-2xl grid place-items-center"><BookOpen/></span>Academic Planner</div><div className="relative max-w-xl"><p className="eyebrow !text-[#c7f36b]">FOCUS · PLAN · PROGRESS</p><h1 className="text-6xl font-black leading-[1.08] mt-5">{locale==="th"?"ทุกเทอมชัดเจน\nทุกเป้าหมายไปถึงได้":"Every semester clear. Every goal within reach."}</h1><p className="mt-6 text-lg text-white/65 max-w-md">{locale==="th"?"รวมเกรด ตารางเรียน งาน และแผนจบไว้ในพื้นที่ทำงานเดียว":"Grades, schedules, deadlines, and degree progress in one focused workspace."}</p></div><p className="text-sm text-white/45">Academic Planner · Public beta</p></section>
    <section className="p-6 sm:p-12 flex items-center justify-center"><div className="w-full max-w-md"><div className="flex justify-between items-center mb-12 lg:hidden"><b>Academic Planner</b><button className="button-secondary" onClick={()=>router.push(`/${locale==="th"?"en":"th"}/login`)}><Languages size={17}/>{locale==="th"?"EN":"ไทย"}</button></div><p className="eyebrow">{mode==="login"?"SECURE SIGN IN":"NEW WORKSPACE"}</p><h2 className="text-4xl font-black mt-3">{mode==="login"?t("title"):t("register")}</h2><p className="text-[var(--muted)] mt-2">{t("subtitle")}</p><form onSubmit={submit} className="mt-9 space-y-4">{mode==="register"&&<label className="block text-sm font-bold">{t("name")}<input required minLength={2} name="name" className="field mt-2"/></label>}<label className="block text-sm font-bold">{t("email")}<input required type="email" name="email" className="field mt-2" autoComplete="email"/></label><label className="block text-sm font-bold">{t("password")}<input required minLength={8} type="password" name="password" className="field mt-2" autoComplete={mode==="login"?"current-password":"new-password"}/></label>{error&&<p role="alert" className="text-sm text-red-700 bg-red-50 p-3 rounded-xl">{error}</p>}<button disabled={pending} className="button-primary w-full">{pending?<LoaderCircle className="animate-spin"/>:mode==="login"?t("title"):t("register")}</button></form><button className="mt-5 text-sm font-bold underline" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?t("register"):t("title")}</button><button className="float-right mt-5 text-sm text-[var(--muted)]" onClick={()=>router.push(`/${locale}`)}>{locale==="th"?"ใช้งานแบบผู้เยี่ยมชม":"Continue as guest"}</button></div></section>
  </main>;
}
