"use client";
import {zodResolver} from "@hookform/resolvers/zod";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {BookOpen,CheckCircle2,GraduationCap,LoaderCircle,Pencil,Plus,Trash2} from "lucide-react";
import {useLocale} from "next-intl";
import {useMemo,useState} from "react";
import {useForm} from "react-hook-form";
import {z} from "zod";
import {apiFetch} from "@/lib/api-client";
import {calculateGpa,cumulativeGpa} from "@/lib/gpa";
import {guestDb,guestLimits} from "@/lib/guest-db";
import {courseCategories,grades,listFrom,type Course,type Semester} from "@/lib/types";
import {Modal} from "./modal";

const semesterSchema=z.object({year:z.number().int().min(1900).max(2200),term:z.string().trim().min(1).max(50),term_no:z.number().int().min(1).max(12),is_complete:z.boolean()});
const courseSchema=z.object({name:z.string().trim().min(1).max(200),course_code:z.string().trim().max(30),credit:z.number().int().min(1).max(30),grade:z.enum(grades),type:z.enum(["ACTUAL","PLAN"]),category:z.enum(courseCategories),instructor:z.string().trim().max(100),notes:z.string().trim().max(2000)});
type SemesterInput=z.infer<typeof semesterSchema>;type CourseInput=z.infer<typeof courseSchema>;

const gradeLabels:Record<string,string>={A:"A",B_PLUS:"B+",B:"B",C_PLUS:"C+",C:"C",D_PLUS:"D+",D:"D",F:"F"};
const categoryLabels={GEN_ED:["ศึกษาทั่วไป","General education"],MAJOR_REQUIRED:["วิชาเอกบังคับ","Major required"],MAJOR_ELECTIVE:["วิชาเอกเลือก","Major elective"],MINOR:["วิชาโท","Minor"],FREE_ELECTIVE:["เลือกเสรี","Free elective"]} as const;

export function AcademicsView({authenticated,authReady}:{authenticated:boolean;authReady:boolean}){
  const locale=useLocale();const th=locale==="th";const queryClient=useQueryClient();
  const [semesterEditor,setSemesterEditor]=useState<Semester|null|"new">(null);const [courseEditor,setCourseEditor]=useState<{semester:Semester;course?:Course}|null>(null);const [notice,setNotice]=useState("");
  const cloud=useQuery({queryKey:["semesters"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("semesters/getSemesters").then((data)=>listFrom<Semester>(data,"semesters"))});
  const guest=useQuery({queryKey:["guest","semesters"],enabled:authReady&&!authenticated,queryFn:()=>guestDb.semesters.toArray()});
  const semesters=useMemo(()=>[...(authenticated?(cloud.data??[]):(guest.data??[]))].sort((a,b)=>b.year-a.year||b.term_no-a.term_no),[authenticated,cloud.data,guest.data]);
  const refresh=async()=>{await queryClient.invalidateQueries({queryKey:authenticated?["semesters"]:["guest","semesters"]});};
  const mutation=useMutation({mutationFn:async(action:()=>Promise<void>)=>action(),onSuccess:async()=>{setNotice(th?"บันทึกเรียบร้อย":"Saved successfully");await refresh();},onError:(error)=>setNotice(error instanceof Error?error.message:String(error))});
  const actual=cumulativeGpa(semesters);const projected=cumulativeGpa(semesters,true);

  async function saveSemester(input:SemesterInput,current?:Semester){
    await mutation.mutateAsync(async()=>{if(authenticated){await apiFetch(`semesters/${current?`updateSemester/${current.id}`:"addSemester"}`,{method:current?"PATCH":"POST",body:JSON.stringify(input)});return;}
      if(!current&&semesters.length>=guestLimits.semesters)throw new Error(th?`โหมดผู้เยี่ยมชมเพิ่มได้สูงสุด ${guestLimits.semesters} เทอม`:`Guest mode supports up to ${guestLimits.semesters} semesters`);
      const semester:Semester=current?{...current,...input}:{...input,id:crypto.randomUUID(),courses:[],gpas:[]};await guestDb.semesters.put(semester);
    });setSemesterEditor(null);
  }
  async function saveCourse(input:CourseInput,semester:Semester,current?:Course){
    await mutation.mutateAsync(async()=>{const payload={...input,semester_id:semester.id,course_code:input.course_code||null,instructor:input.instructor||null,notes:input.notes||null};if(authenticated){await apiFetch(`courses/${current?`editCourse/${current.id}`:"createCourse"}`,{method:current?"PATCH":"POST",body:JSON.stringify(payload)});return;}
      if(!current&&(semester.courses?.length??0)>=guestLimits.coursesPerSemester)throw new Error(th?`แต่ละเทอมเพิ่มได้สูงสุด ${guestLimits.coursesPerSemester} วิชา`:`Each guest semester supports ${guestLimits.coursesPerSemester} courses`);
      const course:Course={...payload,id:current?.id??crypto.randomUUID(),grade_point:0};const courses=current?semester.courses.map((item)=>item.id===current.id?course:item):[...(semester.courses??[]),course];await guestDb.semesters.put({...semester,courses});
    });setCourseEditor(null);
  }
  async function removeSemester(semester:Semester){if(!confirm(th?"ลบเทอมและรายวิชาทั้งหมดในเทอมนี้?":"Delete this semester and all of its courses?"))return;await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`semesters/deleteSemester/${semester.id}`,{method:"DELETE"});else await guestDb.semesters.delete(semester.id);});}
  async function removeCourse(semester:Semester,course:Course){if(!confirm(th?"ลบรายวิชานี้?":"Delete this course?"))return;await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`courses/deleteCourse/${course.id}`,{method:"DELETE"});else await guestDb.semesters.put({...semester,courses:semester.courses.filter((item)=>item.id!==course.id)});});}
  const loading=!authReady||(authenticated&&cloud.isLoading)||(!authenticated&&guest.isLoading);
  if(loading)return <AcademicSkeleton/>;
  return <div className="space-y-6">
    <header className="card p-6 sm:p-8 flex flex-col sm:flex-row sm:items-end gap-5"><div className="flex-1"><p className="eyebrow">ACADEMIC RECORD</p><h2 className="text-3xl sm:text-4xl font-black mt-2">{th?"เทอมและรายวิชา":"Semesters & courses"}</h2><p className="text-[var(--muted)] mt-2">{authenticated?(th?"ซิงก์กับบัญชีของคุณแล้ว":"Synced to your account"):(th?"บันทึกบนอุปกรณ์นี้ในโหมดผู้เยี่ยมชม":"Stored on this device in guest mode")}</p></div><button className="button-primary" onClick={()=>setSemesterEditor("new")}><Plus size={18}/>{th?"เพิ่มเทอม":"Add semester"}</button></header>
    {notice&&<div role="status" className="rounded-2xl border border-[var(--line)] bg-white px-4 py-3 text-sm flex justify-between gap-3"><span>{notice}</span><button onClick={()=>setNotice("")} aria-label="Dismiss">×</button></div>}
    <section className="grid-auto"><Metric icon={GraduationCap} label={th?"GPA ปัจจุบัน":"Current GPA"} value={actual.gpa.toFixed(2)}/><Metric icon={BookOpen} label={th?"GPA รวมวิชาที่วางแผน":"Projected GPA"} value={projected.gpa.toFixed(2)}/><Metric icon={CheckCircle2} label={th?"หน่วยกิตที่เรียนแล้ว":"Completed credits"} value={String(actual.credits)}/></section>
    {cloud.isError&&<ErrorCard message={cloud.error.message} retry={()=>void cloud.refetch()}/>}
    {!semesters.length?<EmptyAcademic onAdd={()=>setSemesterEditor("new")} th={th}/>:<div className="space-y-5">{semesters.map((semester)=><SemesterCard key={semester.id} semester={semester} th={th} busy={mutation.isPending} onEdit={()=>setSemesterEditor(semester)} onDelete={()=>void removeSemester(semester)} onAddCourse={()=>setCourseEditor({semester})} onEditCourse={(course)=>setCourseEditor({semester,course})} onDeleteCourse={(course)=>void removeCourse(semester,course)}/>)}</div>}
    {semesterEditor&&<Modal title={semesterEditor==="new"?(th?"เพิ่มเทอม":"Add semester"):(th?"แก้ไขเทอม":"Edit semester")} onClose={()=>setSemesterEditor(null)}><SemesterForm th={th} initial={semesterEditor==="new"?undefined:semesterEditor} pending={mutation.isPending} onSubmit={(input)=>saveSemester(input,semesterEditor==="new"?undefined:semesterEditor)}/></Modal>}
    {courseEditor&&<Modal title={courseEditor.course?(th?"แก้ไขรายวิชา":"Edit course"):(th?"เพิ่มรายวิชา":"Add course")} onClose={()=>setCourseEditor(null)}><CourseForm th={th} initial={courseEditor.course} pending={mutation.isPending} onSubmit={(input)=>saveCourse(input,courseEditor.semester,courseEditor.course)}/></Modal>}
  </div>;
}

function SemesterCard({semester,th,busy,onEdit,onDelete,onAddCourse,onEditCourse,onDeleteCourse}:{semester:Semester;th:boolean;busy:boolean;onEdit:()=>void;onDelete:()=>void;onAddCourse:()=>void;onEditCourse:(course:Course)=>void;onDeleteCourse:(course:Course)=>void}){
  const actual=calculateGpa(semester.courses??[]);const projected=calculateGpa(semester.courses??[],true);
  return <article className="card overflow-hidden"><div className="p-5 sm:p-6 flex flex-col md:flex-row md:items-center gap-4 border-b border-[var(--line)]"><div className="flex-1"><div className="flex items-center gap-2 flex-wrap"><h3 className="text-xl font-black">{semester.term} {semester.year}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${semester.is_complete?"bg-[#dceae5]":"bg-[#fff0d7]"}`}>{semester.is_complete?(th?"จบแล้ว":"Completed"):(th?"กำลังเรียน/วางแผน":"In progress")}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{semester.courses?.length??0} {th?"รายวิชา":"courses"} · GPA {actual.gpa.toFixed(2)} · {th?"คาดการณ์":"projected"} {projected.gpa.toFixed(2)}</p></div><div className="flex gap-2 flex-wrap"><button className="button-primary" disabled={busy} onClick={onAddCourse}><Plus size={16}/>{th?"เพิ่มวิชา":"Add course"}</button><button className="button-secondary !px-3" disabled={busy} onClick={onEdit} aria-label={th?"แก้ไขเทอม":"Edit semester"}><Pencil size={16}/></button><button className="button-danger !px-3" disabled={busy} onClick={onDelete} aria-label={th?"ลบเทอม":"Delete semester"}><Trash2 size={16}/></button></div></div>
    <div className="divide-y divide-[var(--line)]">{(semester.courses??[]).map((course)=><div key={course.id} className="p-4 sm:px-6 grid sm:grid-cols-[1fr_auto_auto] items-center gap-3"><div><div className="flex gap-2 items-center"><b>{course.course_code&&<span className="text-[var(--muted)] mr-2">{course.course_code}</span>}{course.name}</b><span className={`rounded-full px-2 py-0.5 text-[.68rem] font-black ${course.type==="ACTUAL"?"bg-[#eaf8c8]":"bg-[#ffebe6]"}`}>{course.type}</span></div><p className="text-xs text-[var(--muted)] mt-1">{categoryLabels[course.category][th?0:1]} · {course.credit} {th?"หน่วยกิต":"credits"}{course.instructor?` · ${course.instructor}`:""}</p></div><div className="text-left sm:text-right"><span className="text-2xl font-black">{gradeLabels[course.grade]}</span></div><div className="flex gap-1"><button className="button-secondary !min-h-9 !p-2" onClick={()=>onEditCourse(course)} aria-label={th?"แก้ไขรายวิชา":"Edit course"}><Pencil size={15}/></button><button className="button-danger !min-h-9 !p-2" onClick={()=>onDeleteCourse(course)} aria-label={th?"ลบรายวิชา":"Delete course"}><Trash2 size={15}/></button></div></div>)}{!semester.courses?.length&&<div className="p-8 text-center text-sm text-[var(--muted)]">{th?"ยังไม่มีรายวิชาในเทอมนี้":"No courses in this semester yet"}</div>}</div>
  </article>;
}

function SemesterForm({th,initial,pending,onSubmit}:{th:boolean;initial?:Semester;pending:boolean;onSubmit:(input:SemesterInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<SemesterInput>({resolver:zodResolver(semesterSchema),defaultValues:{year:initial?.year??new Date().getFullYear(),term:initial?.term??(th?"ภาคเรียนที่ 1":"Semester 1"),term_no:initial?.term_no??1,is_complete:initial?.is_complete??false}});return <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}><div className="grid sm:grid-cols-2 gap-4"><Field label={th?"ปีการศึกษา (ค.ศ.)":"Academic year"} error={errors.year?.message}><input className="field" type="number" {...register("year",{valueAsNumber:true})}/></Field><Field label={th?"ลำดับเทอม":"Term number"} error={errors.term_no?.message}><input className="field" type="number" {...register("term_no",{valueAsNumber:true})}/></Field></div><Field label={th?"ชื่อเทอม":"Term name"} error={errors.term?.message}><input className="field" {...register("term")}/></Field><label className="flex gap-3 items-center rounded-xl border border-[var(--line)] p-3"><input type="checkbox" {...register("is_complete")}/><span className="text-sm font-bold">{th?"เรียนจบเทอมนี้แล้ว":"This semester is complete"}</span></label><button className="button-primary w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={18}/>:null}{th?"บันทึกเทอม":"Save semester"}</button></form>}

function CourseForm({th,initial,pending,onSubmit}:{th:boolean;initial?:Course;pending:boolean;onSubmit:(input:CourseInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<CourseInput>({resolver:zodResolver(courseSchema),defaultValues:{name:initial?.name??"",course_code:initial?.course_code??"",credit:initial?.credit??3,grade:initial?.grade??"A",type:initial?.type??"PLAN",category:initial?.category??"MAJOR_REQUIRED",instructor:initial?.instructor??"",notes:initial?.notes??""}});return <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}><div className="grid sm:grid-cols-[.7fr_1.3fr] gap-4"><Field label={th?"รหัสวิชา":"Course code"}><input className="field" {...register("course_code")}/></Field><Field label={th?"ชื่อวิชา":"Course name"} error={errors.name?.message}><input className="field" {...register("name")}/></Field></div><div className="grid sm:grid-cols-3 gap-4"><Field label={th?"หน่วยกิต":"Credits"}><input className="field" type="number" {...register("credit",{valueAsNumber:true})}/></Field><Field label={th?"เกรด":"Grade"}><select className="field" {...register("grade")}>{grades.map((grade)=><option key={grade} value={grade}>{gradeLabels[grade]}</option>)}</select></Field><Field label={th?"สถานะ":"Status"}><select className="field" {...register("type")}><option value="PLAN">{th?"วางแผน":"Planned"}</option><option value="ACTUAL">{th?"ผลจริง":"Actual"}</option></select></Field></div><Field label={th?"หมวดวิชา":"Category"}><select className="field" {...register("category")}>{courseCategories.map((category)=><option key={category} value={category}>{categoryLabels[category][th?0:1]}</option>)}</select></Field><Field label={th?"ผู้สอน (ไม่บังคับ)":"Instructor (optional)"}><input className="field" {...register("instructor")}/></Field><Field label={th?"บันทึก (ไม่บังคับ)":"Notes (optional)"}><textarea className="field min-h-24" {...register("notes")}/></Field><button className="button-primary w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={18}/>:null}{th?"บันทึกรายวิชา":"Save course"}</button></form>}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-bold">{label}<span className="block mt-2">{children}</span>{error&&<span className="block text-xs text-red-700 mt-1">{error}</span>}</label>}
function Metric({icon:Icon,label,value}:{icon:typeof GraduationCap;label:string;value:string}){return <article className="card p-5 flex gap-4 items-center"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eaf8c8]"><Icon size={20}/></span><div><p className="text-sm text-[var(--muted)]">{label}</p><strong className="text-2xl font-black">{value}</strong></div></article>}
function EmptyAcademic({onAdd,th}:{onAdd:()=>void;th:boolean}){return <section className="card min-h-80 grid place-items-center p-8 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-[#eaf8c8]"><BookOpen/></span><h3 className="text-xl font-black mt-5">{th?"เริ่มต้นด้วยเทอมแรก":"Start with your first semester"}</h3><p className="text-[var(--muted)] mt-2">{th?"เพิ่มเทอม รายวิชา เกรดจริง และเกรดที่วางแผนไว้":"Add terms, courses, actual grades, and planned grades"}</p><button className="button-primary mt-5" onClick={onAdd}><Plus size={18}/>{th?"เพิ่มเทอม":"Add semester"}</button></div></section>}
function ErrorCard({message,retry}:{message:string;retry:()=>void}){return <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800 flex justify-between gap-4"><span>{message}</span><button className="font-bold underline" onClick={retry}>Retry</button></div>}
function AcademicSkeleton(){return <div className="space-y-5"><div className="skeleton h-36 rounded-3xl"/><div className="grid-auto"><div className="skeleton h-28 rounded-3xl"/><div className="skeleton h-28 rounded-3xl"/></div><div className="skeleton h-72 rounded-3xl"/></div>}
