"use client";
import {zodResolver} from "@hookform/resolvers/zod";
import {Languages,LoaderCircle,LockKeyhole,LogIn,LogOut,MonitorCog,Shield,Trash2,UserRound} from "lucide-react";
import {useLocale} from "next-intl";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useState} from "react";
import {useForm} from "react-hook-form";
import {z} from "zod";
import {useAuth} from "./providers";
import {accountAction} from "@/lib/api-client";
import {clearGuest} from "@/lib/guest-db";
import type {User} from "@/lib/types";
import {PushSettings} from "./push-settings";
import {useTheme} from "./theme-provider";

const profileSchema=z.object({name:z.string().trim().min(2).max(100),email:z.string().trim().email()});
const passwordSchema=z.object({current_password:z.string().min(1).max(72),new_password:z.string().min(8).max(32),confirm_password:z.string()}).refine((value)=>value.new_password===value.confirm_password,{message:"Passwords do not match",path:["confirm_password"]});
type ProfileInput=z.infer<typeof profileSchema>;type PasswordInput=z.infer<typeof passwordSchema>;

export function AccountView({authenticated}:{authenticated:boolean}){
  const locale=useLocale();const th=locale==="th";const router=useRouter();const auth=useAuth();const [pendingAction,setPendingAction]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function run(action:string,work:()=>Promise<void>){setPendingAction(action);setMessage("");setError("");try{await work();}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setPendingAction("");}}
  async function logoutEverywhere(){if(!confirm(th?"ออกจากระบบทุกอุปกรณ์?":"Sign out on every device?"))return;await run("logout-all",async()=>{await auth.logoutAll();router.replace(`/${locale}/login`);});}
  async function removeAccount(password:string){if(!confirm(th?"ลบบัญชีและข้อมูลทั้งหมดอย่างถาวร? การดำเนินการนี้ย้อนกลับไม่ได้":"Permanently delete your account and all data? This cannot be undone."))return;await run("delete",async()=>{await accountAction("delete-account","DELETE",{password});auth.clearSession();router.replace(`/${locale}`);});}
  async function clearDevice(){if(!confirm(th?"ลบข้อมูลโหมดผู้เยี่ยมชมทั้งหมดบนอุปกรณ์นี้?":"Delete all guest data on this device?"))return;await run("clear",async()=>{await clearGuest();setMessage(th?"ล้างข้อมูลบนอุปกรณ์แล้ว":"Device data cleared");});}
  if(!auth.ready)return <div className="skeleton h-80 rounded-[var(--radius-lg)]"/>;
  return <div className="space-y-6"><header className="card page-header"><div><p className="eyebrow">ACCOUNT & SETTINGS</p><h2 className="page-title">{th?"บัญชี ความเป็นส่วนตัว และการตั้งค่า":"Account, privacy & preferences"}</h2><p className="page-description">{authenticated?(th?"จัดการข้อมูลส่วนตัวและ session ที่เชื่อมกับบัญชี":"Manage your profile and active account sessions"):(th?"คุณกำลังใช้โหมดผู้เยี่ยมชม ข้อมูลเก็บเฉพาะบนอุปกรณ์นี้":"You are in guest mode; data stays on this device")}</p></div></header>
    {message&&<div role="status" className="notice notice-success">{message}</div>}{error&&<div role="alert" className="notice notice-error">{error}</div>}
    {authenticated&&auth.user?<section className="grid xl:grid-cols-2 gap-5"><article className="card p-6"><div className="flex gap-3 items-center"><UserRound/><div><p className="eyebrow">PROFILE</p><h3 className="font-black text-xl">{th?"ข้อมูลส่วนตัว":"Personal details"}</h3></div></div><ProfileForm th={th} user={auth.user} pending={pendingAction==="profile"} onSubmit={(input)=>run("profile",async()=>{const result=await accountAction<{user:User}>("profile","PATCH",input);auth.updateUser(result.user);setMessage(th?"อัปเดตโปรไฟล์แล้ว":"Profile updated");})}/></article><article className="card p-6"><div className="flex gap-3 items-center"><LockKeyhole/><div><p className="eyebrow">SECURITY</p><h3 className="font-black text-xl">{th?"เปลี่ยนรหัสผ่าน":"Change password"}</h3></div></div><PasswordForm th={th} pending={pendingAction==="password"} onSubmit={(input)=>run("password",async()=>{await accountAction("change-password","POST",{current_password:input.current_password,new_password:input.new_password});setMessage(th?"เปลี่ยนรหัสผ่านแล้ว":"Password changed");})}/></article></section>:<section className="card p-7 sm:p-9 flex flex-col sm:flex-row gap-5 sm:items-center"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-[#eaf8c8]"><LogIn/></span><div className="flex-1"><h3 className="font-black text-xl">{th?"เชื่อมบัญชีเพื่อซิงก์ข้อมูล":"Connect an account to sync"}</h3><p className="text-[var(--muted)] mt-1">{th?"เข้าถึงข้อมูลจากอุปกรณ์อื่นและสำรองไว้บนคลาวด์":"Access your plan from other devices and keep a cloud backup"}</p></div><Link className="button-primary" href={`/${locale}/login`}>{th?"เข้าสู่ระบบหรือสมัคร":"Sign in or register"}</Link></section>}
    <section className="grid lg:grid-cols-2 gap-5"><Preferences th={th} locale={locale} onLocale={(next)=>router.push(`/${next}/account`)}/>{authenticated?<PushSettings/>:<article className="card p-6"><BellNotice th={th}/></article>}<article className="card p-6"><div className="flex gap-3 items-center"><Shield/><div><p className="eyebrow">LEGAL</p><h3 className="font-black text-xl">{th?"สิทธิและความเป็นส่วนตัว":"Rights & privacy"}</h3></div></div><div className="mt-5 grid gap-3"><Link className="button-secondary !justify-between" href={`/${locale}/privacy`}>{th?"นโยบายความเป็นส่วนตัว":"Privacy policy"}<span>→</span></Link><Link className="button-secondary !justify-between" href={`/${locale}/terms`}>{th?"ข้อกำหนดการใช้งาน":"Terms of use"}<span>→</span></Link></div></article></section>
    <section className="card p-6 border-red-200"><p className="eyebrow !text-red-700">DANGER ZONE</p><div className="mt-4 space-y-4">{authenticated?<><div className="flex flex-col sm:flex-row gap-4 sm:items-center"><div className="flex-1"><h3 className="font-black">{th?"ออกจากระบบทุกอุปกรณ์":"Sign out everywhere"}</h3><p className="text-sm text-[var(--muted)]">{th?"ยกเลิก refresh sessions ทุกอุปกรณ์ที่เชื่อมต่อ":"Revoke every refresh session connected to your account"}</p></div><button className="button-secondary" disabled={!!pendingAction} onClick={()=>void logoutEverywhere()}>{pendingAction==="logout-all"?<LoaderCircle className="animate-spin" size={17}/>:<LogOut size={17}/>} {th?"ออกจากระบบทั้งหมด":"Sign out all"}</button></div><DeleteAccount th={th} pending={pendingAction==="delete"} onDelete={removeAccount}/></>:<div className="flex flex-col sm:flex-row gap-4 sm:items-center"><div className="flex-1"><h3 className="font-black">{th?"ล้างข้อมูลบนอุปกรณ์":"Clear device data"}</h3><p className="text-sm text-[var(--muted)]">{th?"ลบเทอม วิชา เป้าหมาย งาน และตารางเรียนในโหมดผู้เยี่ยมชม":"Delete guest semesters, courses, goals, tasks, and schedule"}</p></div><button className="button-danger" disabled={!!pendingAction} onClick={()=>void clearDevice()}>{pendingAction==="clear"?<LoaderCircle className="animate-spin" size={17}/>:<Trash2 size={17}/>} {th?"ล้างข้อมูล":"Clear data"}</button></div>}</div></section>
  </div>;
}

function ProfileForm({th,user,pending,onSubmit}:{th:boolean;user:User;pending:boolean;onSubmit:(value:ProfileInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<ProfileInput>({resolver:zodResolver(profileSchema),defaultValues:{name:user.name,email:user.email}});return <form className="mt-6 space-y-4" onSubmit={handleSubmit(onSubmit)}><label className="block text-sm font-bold">{th?"ชื่อ":"Name"}<input className="field mt-2" {...register("name")}/>{errors.name&&<span className="text-xs text-red-700">{errors.name.message}</span>}</label><label className="block text-sm font-bold">{th?"อีเมล":"Email"}<input type="email" className="field mt-2" {...register("email")}/>{errors.email&&<span className="text-xs text-red-700">{errors.email.message}</span>}</label><button className="button-primary w-full" disabled={pending}>{pending&&<LoaderCircle className="animate-spin" size={17}/>} {th?"บันทึกโปรไฟล์":"Save profile"}</button></form>}
function PasswordForm({th,pending,onSubmit}:{th:boolean;pending:boolean;onSubmit:(value:PasswordInput)=>Promise<void>}){const {register,handleSubmit,reset,formState:{errors}}=useForm<PasswordInput>({resolver:zodResolver(passwordSchema)});return <form className="mt-6 space-y-4" onSubmit={handleSubmit(async(value)=>{await onSubmit(value);reset();})}><label className="block text-sm font-bold">{th?"รหัสผ่านปัจจุบัน":"Current password"}<input type="password" autoComplete="current-password" className="field mt-2" {...register("current_password")}/></label><label className="block text-sm font-bold">{th?"รหัสผ่านใหม่":"New password"}<input type="password" autoComplete="new-password" className="field mt-2" {...register("new_password")}/></label><label className="block text-sm font-bold">{th?"ยืนยันรหัสผ่านใหม่":"Confirm new password"}<input type="password" autoComplete="new-password" className="field mt-2" {...register("confirm_password")}/>{errors.confirm_password&&<span className="text-xs text-red-700">{errors.confirm_password.message}</span>}</label><button className="button-primary w-full" disabled={pending}>{pending&&<LoaderCircle className="animate-spin" size={17}/>} {th?"เปลี่ยนรหัสผ่าน":"Change password"}</button></form>}
function Preferences({th,locale,onLocale}:{th:boolean;locale:string;onLocale:(locale:string)=>void}){const {preference,setTheme}=useTheme();return <article className="card p-6"><div className="flex items-center gap-3"><span className="icon-tile"><MonitorCog size={20}/></span><div><p className="eyebrow">PREFERENCES</p><h3 className="section-heading">{th?"ภาษาและธีม":"Language & theme"}</h3></div></div><div className="mt-5 space-y-4"><label className="block text-sm font-bold"><span className="flex gap-2"><Languages size={16}/>{th?"ภาษา":"Language"}</span><select className="field mt-2" value={locale} onChange={(event)=>onLocale(event.target.value)}><option value="th">ไทย</option><option value="en">English</option></select></label><label className="block text-sm font-bold">{th?"ธีม":"Theme"}<select className="field mt-2" value={preference} onChange={(event)=>setTheme(event.target.value as "light"|"dark"|"system")}><option value="system">{th?"ตามระบบ":"System"}</option><option value="light">{th?"สว่าง":"Light"}</option><option value="dark">{th?"มืด":"Dark"}</option></select></label></div></article>}
function DeleteAccount({th,pending,onDelete}:{th:boolean;pending:boolean;onDelete:(password:string)=>Promise<void>}){const [password,setPassword]=useState("");return <div className="border-t border-red-100 pt-4 flex flex-col sm:flex-row gap-4 sm:items-end"><label className="flex-1 text-sm font-bold">{th?"ลบบัญชีถาวร—กรอกรหัสผ่านเพื่อยืนยัน":"Delete account—enter your password to confirm"}<input type="password" className="field mt-2" value={password} onChange={(event)=>setPassword(event.target.value)}/></label><button className="button-danger" disabled={pending||!password} onClick={()=>void onDelete(password)}>{pending?<LoaderCircle className="animate-spin" size={17}/>:<Trash2 size={17}/>} {th?"ลบบัญชี":"Delete account"}</button></div>}
function BellNotice({th}:{th:boolean}){return <div><p className="eyebrow">WEB PUSH</p><h3 className="font-black text-xl mt-1">{th?"เข้าสู่ระบบเพื่อเปิดการแจ้งเตือน":"Sign in to enable notifications"}</h3><p className="text-sm text-[var(--muted)] mt-3">{th?"การแจ้งเตือนจะซิงก์กับงานในบัญชีของคุณ":"Notifications are synced with tasks in your account"}</p></div>}
