"use client";
import {zodResolver} from "@hookform/resolvers/zod";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Check,Flag,LoaderCircle,Pencil,Plus,Target,Trash2,Trophy} from "lucide-react";
import {useLocale} from "next-intl";
import {useMemo,useState} from "react";
import {useForm} from "react-hook-form";
import {z} from "zod";
import {apiFetch} from "@/lib/api-client";
import {calculateGpa} from "@/lib/gpa";
import {guestDb,guestLimits} from "@/lib/guest-db";
import {listFrom,type Goal,type Semester} from "@/lib/types";
import {Modal} from "./modal";

const goalSchema=z.object({name:z.string().trim().min(1).max(100),target_gpa:z.number().min(0).max(4),target_semester_id:z.string().min(1),is_achieved:z.boolean()});
type GoalInput=z.infer<typeof goalSchema>;

export function GoalsView({authenticated,authReady}:{authenticated:boolean;authReady:boolean}){
  const locale=useLocale();const th=locale==="th";const queryClient=useQueryClient();const [editor,setEditor]=useState<Goal|null|"new">(null);const [message,setMessage]=useState("");
  const cloudSemesters=useQuery({queryKey:["semesters"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("semesters/getSemesters").then((data)=>listFrom<Semester>(data,"semesters"))});
  const cloudGoals=useQuery({queryKey:["goals"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("goals/getGoalByUserId").then((data)=>listFrom<Goal>(data,"goals"))});
  const guest=useQuery({queryKey:["guest","goals-bundle"],enabled:authReady&&!authenticated,queryFn:async()=>{const [goals,semesters]=await Promise.all([guestDb.goals.toArray(),guestDb.semesters.toArray()]);return {goals,semesters};}});
  const goals=authenticated?(cloudGoals.data??[]):(guest.data?.goals??[]);const semesters=useMemo(()=>[...(authenticated?(cloudSemesters.data??[]):(guest.data?.semesters??[]))].sort((a,b)=>b.year-a.year||b.term_no-a.term_no),[authenticated,cloudSemesters.data,guest.data]);
  const refresh=async()=>{if(authenticated)await Promise.all([queryClient.invalidateQueries({queryKey:["goals"]}),queryClient.invalidateQueries({queryKey:["semesters"]})]);else await guest.refetch();};
  const mutation=useMutation({mutationFn:async(action:()=>Promise<void>)=>action(),onSuccess:async()=>{setMessage(th?"อัปเดตเป้าหมายแล้ว":"Goal updated");await refresh();},onError:(error)=>setMessage(error instanceof Error?error.message:String(error))});
  async function save(input:GoalInput,current?:Goal){await mutation.mutateAsync(async()=>{if(authenticated){await apiFetch(`goals/${current?`updateGoal/${current.id}`:"createGoal"}`,{method:current?"PATCH":"POST",body:JSON.stringify(input)});return;}if(!current&&goals.length>=guestLimits.goals)throw new Error(th?`เพิ่มเป้าหมายได้สูงสุด ${guestLimits.goals} รายการ`:`Guest mode supports ${guestLimits.goals} goals`);await guestDb.goals.put(current?{...current,...input}:{...input,id:crypto.randomUUID()});});setEditor(null);}
  async function toggle(goal:Goal){await mutation.mutateAsync(async()=>{const next={...goal,is_achieved:!goal.is_achieved};if(authenticated)await apiFetch(`goals/updateGoal/${goal.id}`,{method:"PATCH",body:JSON.stringify({is_achieved:next.is_achieved})});else await guestDb.goals.put(next);});}
  async function remove(goal:Goal){if(!confirm(th?"ลบเป้าหมายนี้?":"Delete this goal?"))return;await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`goals/deleteGoal/${goal.id}`,{method:"DELETE"});else await guestDb.goals.delete(goal.id);});}
  const loading=!authReady||(authenticated&&(cloudGoals.isLoading||cloudSemesters.isLoading))||(!authenticated&&guest.isLoading);
  if(loading)return <div className="space-y-5"><div className="skeleton h-40 rounded-3xl"/><div className="grid-auto"><div className="skeleton h-48 rounded-3xl"/><div className="skeleton h-48 rounded-3xl"/></div></div>;
  return <div className="space-y-6"><header className="card bg-[var(--forest)] !text-white p-7 sm:p-9 relative overflow-hidden"><span className="absolute -right-12 -top-16 h-56 w-56 rounded-full bg-[var(--lime)]/20"/><div className="relative flex flex-col sm:flex-row sm:items-end gap-5"><div className="flex-1"><p className="eyebrow !text-[#c7f36b]">GPA GOALS</p><h2 className="text-3xl sm:text-5xl font-black mt-2">{th?"เป้าหมายที่วัดผลได้":"Goals you can measure"}</h2><p className="text-white/65 mt-3">{th?"กำหนด GPA เป้าหมายสำหรับแต่ละเทอมและติดตามความคืบหน้า":"Set a GPA target for a semester and follow your progress"}</p></div><button className="button-primary !bg-[var(--lime)] !text-[var(--forest)]" disabled={!semesters.length} onClick={()=>setEditor("new")}><Plus size={18}/>{th?"เพิ่มเป้าหมาย":"Add goal"}</button></div></header>
    {message&&<div role="status" className="rounded-2xl border border-[var(--line)] bg-white px-4 py-3 text-sm flex justify-between"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
    {!semesters.length?<section className="card p-8 text-center"><Flag className="mx-auto"/><h3 className="font-black text-xl mt-4">{th?"เพิ่มเทอมก่อนตั้งเป้าหมาย":"Add a semester before setting a goal"}</h3><p className="text-[var(--muted)] mt-2">{th?"เป้าหมาย GPA ต้องเชื่อมกับเทอมปลายทาง":"Each GPA goal needs a target semester"}</p></section>:!goals.length?<section className="card min-h-72 grid place-items-center p-8 text-center"><div><Target className="mx-auto" size={34}/><h3 className="font-black text-xl mt-4">{th?"ยังไม่มีเป้าหมาย":"No goals yet"}</h3><button className="button-primary mt-5" onClick={()=>setEditor("new")}><Plus size={18}/>{th?"สร้างเป้าหมายแรก":"Create first goal"}</button></div></section>:<section className="grid lg:grid-cols-2 gap-5">{goals.map((goal)=>{const semester=semesters.find((item)=>item.id===goal.target_semester_id);const current=semester?calculateGpa(semester.courses??[],true).gpa:0;const progress=Math.min(100,goal.target_gpa?current/goal.target_gpa*100:100);return <article key={goal.id} className="card p-6"><div className="flex gap-3 items-start"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${goal.is_achieved?"bg-[#eaf8c8]":"bg-[#ffebe6]"}`}>{goal.is_achieved?<Trophy size={20}/>:<Target size={20}/>}</span><div className="flex-1"><h3 className="font-black text-lg">{goal.name}</h3><p className="text-sm text-[var(--muted)] mt-1">{semester?`${semester.term} ${semester.year}`:(th?"ไม่พบเทอม":"Semester unavailable")}</p></div><button className="button-secondary !min-h-9 !p-2" onClick={()=>setEditor(goal)} aria-label={th?"แก้ไข":"Edit"}><Pencil size={15}/></button><button className="button-danger !min-h-9 !p-2" onClick={()=>void remove(goal)} aria-label={th?"ลบ":"Delete"}><Trash2 size={15}/></button></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-[var(--muted)]">{th?"ปัจจุบัน / เป้าหมาย":"Current / target"}</p><strong className="text-3xl font-black">{current.toFixed(2)} <span className="text-base text-[var(--muted)]">/ {goal.target_gpa.toFixed(2)}</span></strong></div><span className="text-sm font-black">{Math.round(progress)}%</span></div><div className="mt-3 h-2.5 overflow-hidden rounded-full bg-[#e7ebe5]"><div className="h-full rounded-full bg-[var(--forest)]" style={{width:`${progress}%`}}/></div><button className={`mt-5 w-full ${goal.is_achieved?"button-secondary":"button-primary"}`} disabled={mutation.isPending} onClick={()=>void toggle(goal)}><Check size={17}/>{goal.is_achieved?(th?"ทำเครื่องหมายว่ายังไม่สำเร็จ":"Mark as active"):(th?"ทำเครื่องหมายว่าสำเร็จ":"Mark achieved")}</button></article>})}</section>}
    {editor&&<Modal title={editor==="new"?(th?"เพิ่มเป้าหมาย":"Add goal"):(th?"แก้ไขเป้าหมาย":"Edit goal")} onClose={()=>setEditor(null)}><GoalForm th={th} semesters={semesters} initial={editor==="new"?undefined:editor} pending={mutation.isPending} onSubmit={(input)=>save(input,editor==="new"?undefined:editor)}/></Modal>}
  </div>;
}

function GoalForm({th,semesters,initial,pending,onSubmit}:{th:boolean;semesters:Semester[];initial?:Goal;pending:boolean;onSubmit:(input:GoalInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<GoalInput>({resolver:zodResolver(goalSchema),defaultValues:{name:initial?.name??(th?"GPA ตามเป้าหมาย":"Target GPA"),target_gpa:initial?.target_gpa??3.5,target_semester_id:initial?.target_semester_id??semesters[0]?.id,is_achieved:initial?.is_achieved??false}});return <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}><label className="block text-sm font-bold">{th?"ชื่อเป้าหมาย":"Goal name"}<input className="field mt-2" {...register("name")}/>{errors.name&&<span className="text-xs text-red-700">{errors.name.message}</span>}</label><div className="grid sm:grid-cols-2 gap-4"><label className="block text-sm font-bold">{th?"GPA เป้าหมาย":"Target GPA"}<input className="field mt-2" type="number" min="0" max="4" step="0.01" {...register("target_gpa",{valueAsNumber:true})}/></label><label className="block text-sm font-bold">{th?"เทอมเป้าหมาย":"Target semester"}<select className="field mt-2" {...register("target_semester_id")}>{semesters.map((semester)=><option key={semester.id} value={semester.id}>{semester.term} {semester.year}</option>)}</select></label></div><label className="flex gap-3 items-center rounded-xl border border-[var(--line)] p-3"><input type="checkbox" {...register("is_achieved")}/><span className="text-sm font-bold">{th?"บรรลุเป้าหมายแล้ว":"Goal achieved"}</span></label><button className="button-primary w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={18}/>:null}{th?"บันทึกเป้าหมาย":"Save goal"}</button></form>}
