"use client";
import {zodResolver} from "@hookform/resolvers/zod";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Bell,BookMarked,CalendarClock,Check,ChevronRight,Clock,GraduationCap,LoaderCircle,MapPin,Pencil,Plus,Trash2} from "lucide-react";
import {useLocale} from "next-intl";
import {useMemo,useState} from "react";
import {useForm} from "react-hook-form";
import {z} from "zod";
import {apiFetch} from "@/lib/api-client";
import {guestDb,guestLimits} from "@/lib/guest-db";
import {formatMinute,meetingsOverlap,minutes,reminderLabel,toLocalInput} from "@/lib/planner";
import {listFrom,taskTypes,type AcademicTask,type Course,type Meeting,type Requirement,type Semester} from "@/lib/types";
import {Modal} from "./modal";

const taskSchema=z.object({title:z.string().trim().min(1).max(200),type:z.enum(taskTypes),course_id:z.string().min(1),due_local:z.string().min(1),notes:z.string().trim().max(2000),reminder_offset_minutes:z.number().int().min(-1).max(43200)});
const meetingSchema=z.object({course_id:z.string().min(1),weekday:z.number().int().min(1).max(7),start_time:z.string().regex(/^\d{2}:\d{2}$/),end_time:z.string().regex(/^\d{2}:\d{2}$/),location:z.string().trim().max(200)}).refine((value)=>minutes(value.end_time)>minutes(value.start_time),{message:"End time must be after start time",path:["end_time"]});
const requirementSchema=z.object({name:z.string().trim().min(1).max(100),required_credits:z.number().int().min(1).max(999),color:z.string().regex(/^#[0-9a-f]{6}$/i)});
type TaskInput=z.infer<typeof taskSchema>;type MeetingInput=z.infer<typeof meetingSchema>;type RequirementInput=z.infer<typeof requirementSchema>;
type Tab="tasks"|"schedule"|"requirements";
const typeNames={ASSIGNMENT:["งาน","Assignment"],EXAM:["สอบ","Exam"],QUIZ:["ควิซ","Quiz"],PROJECT:["โปรเจกต์","Project"],OTHER:["อื่น ๆ","Other"]} as const;
const weekdays=[["จันทร์","Monday"],["อังคาร","Tuesday"],["พุธ","Wednesday"],["พฤหัสบดี","Thursday"],["ศุกร์","Friday"],["เสาร์","Saturday"],["อาทิตย์","Sunday"]] as const;

export function PlannerView({authenticated,authReady}:{authenticated:boolean;authReady:boolean}){
  const locale=useLocale();const th=locale==="th";const queryClient=useQueryClient();const [tab,setTab]=useState<Tab>("tasks");const [taskEditor,setTaskEditor]=useState<AcademicTask|null|"new">(null);const [meetingEditor,setMeetingEditor]=useState(false);const [requirementEditor,setRequirementEditor]=useState<Requirement|null|"new">(null);const [message,setMessage]=useState("");
  const semestersQuery=useQuery({queryKey:["semesters"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("semesters/getSemesters").then((data)=>listFrom<Semester>(data,"semesters"))});
  const tasksQuery=useQuery({queryKey:["planner","tasks"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("planner/tasks").then((data)=>listFrom<AcademicTask>(data))});
  const meetingsQuery=useQuery({queryKey:["planner","schedule"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("planner/schedule").then((data)=>listFrom<Meeting>(data))});
  const requirementsQuery=useQuery({queryKey:["planner","requirements"],enabled:authReady&&authenticated,queryFn:()=>apiFetch("planner/requirements").then((data)=>listFrom<Requirement>(data))});
  const guestQuery=useQuery({queryKey:["guest","planner"],enabled:authReady&&!authenticated,queryFn:async()=>{const [semesters,tasks,meetings,requirements]=await Promise.all([guestDb.semesters.toArray(),guestDb.tasks.toArray(),guestDb.meetings.toArray(),guestDb.requirements.toArray()]);return {semesters,tasks,meetings,requirements};}});
  const semesters=useMemo(()=>authenticated?(semestersQuery.data??[]):(guestQuery.data?.semesters??[]),[authenticated,semestersQuery.data,guestQuery.data]);const courses=useMemo(()=>semesters.flatMap((semester)=>semester.courses??[]),[semesters]);const tasks=authenticated?(tasksQuery.data??[]):(guestQuery.data?.tasks??[]);const meetings=authenticated?(meetingsQuery.data??[]):(guestQuery.data?.meetings??[]);const rawRequirements=useMemo(()=>authenticated?(requirementsQuery.data??[]):(guestQuery.data?.requirements??[]),[authenticated,requirementsQuery.data,guestQuery.data]);
  const requirements=useMemo(()=>rawRequirements.map((requirement)=>{if(authenticated)return requirement;const assigned=courses.filter((course)=>course.requirement_id===requirement.id);return {...requirement,actual_credits:assigned.filter((course)=>course.type==="ACTUAL").reduce((sum,course)=>sum+course.credit,0),projected_credits:assigned.reduce((sum,course)=>sum+course.credit,0)};}),[rawRequirements,courses,authenticated]);
  const refresh=async()=>{if(authenticated)await Promise.all([queryClient.invalidateQueries({queryKey:["planner"]}),queryClient.invalidateQueries({queryKey:["semesters"]})]);else await Promise.all([guestQuery.refetch(),queryClient.invalidateQueries({queryKey:["guest","semesters"]}),queryClient.invalidateQueries({queryKey:["guest","goals-bundle"]})]);};
  const mutation=useMutation({mutationFn:async(action:()=>Promise<void>)=>action(),onSuccess:async()=>{setMessage(th?"บันทึกแพลนเนอร์แล้ว":"Planner updated");await refresh();},onError:(error)=>setMessage(error instanceof Error?error.message:String(error))});
  async function saveTask(input:TaskInput,current?:AcademicTask){await mutation.mutateAsync(async()=>{const course=courses.find((item)=>item.id===input.course_id);if(!course)throw new Error(th?"กรุณาเลือกรายวิชา":"Please select a course");const payload={title:input.title,type:input.type,due_at:new Date(input.due_local).toISOString(),notes:input.notes||null,reminder_offset_minutes:input.reminder_offset_minutes<0?null:input.reminder_offset_minutes};if(authenticated){await apiFetch(`planner/${current?`tasks/${current.id}`:`courses/${course.id}/tasks`}`,{method:current?"PATCH":"POST",body:JSON.stringify(payload)});return;}if(!current&&tasks.length>=guestLimits.tasks)throw new Error(th?`เพิ่มงานได้สูงสุด ${guestLimits.tasks} รายการ`:`Guest mode supports ${guestLimits.tasks} tasks`);await guestDb.tasks.put({...payload,id:current?.id??crypto.randomUUID(),course_id:course.id,is_complete:current?.is_complete??false,course:{id:course.id,name:course.name,course_code:course.course_code}});});setTaskEditor(null);}
  async function toggleTask(task:AcademicTask){await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`planner/tasks/${task.id}`,{method:"PATCH",body:JSON.stringify({is_complete:!task.is_complete})});else await guestDb.tasks.put({...task,is_complete:!task.is_complete});});}
  async function deleteTask(task:AcademicTask){if(!confirm(th?"ลบงานนี้?":"Delete this task?"))return;await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`planner/tasks/${task.id}`,{method:"DELETE"});else await guestDb.tasks.delete(task.id);});}
  async function saveMeeting(input:MeetingInput){await mutation.mutateAsync(async()=>{const course=courses.find((item)=>item.id===input.course_id);if(!course)throw new Error(th?"กรุณาเลือกรายวิชา":"Please select a course");const payload={weekday:input.weekday,start_minute:minutes(input.start_time),end_minute:minutes(input.end_time),location:input.location||null};if(authenticated){await apiFetch(`planner/courses/${course.id}/meetings`,{method:"POST",body:JSON.stringify(payload)});return;}if(meetings.length>=guestLimits.meetings)throw new Error(th?`เพิ่มเวลาเรียนได้สูงสุด ${guestLimits.meetings} รายการ`:`Guest mode supports ${guestLimits.meetings} meetings`);if(meetings.some((item)=>meetingsOverlap(item,payload)))throw new Error(th?"เวลาเรียนทับซ้อนกับวิชาอื่น":"Meeting overlaps another course");await guestDb.meetings.put({...payload,id:crypto.randomUUID(),course_id:course.id,course:{id:course.id,name:course.name,course_code:course.course_code}});});setMeetingEditor(false);}
  async function deleteMeeting(meeting:Meeting){await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`planner/meetings/${meeting.id}`,{method:"DELETE"});else await guestDb.meetings.delete(meeting.id);});}
  async function saveRequirement(input:RequirementInput,current?:Requirement){await mutation.mutateAsync(async()=>{const payload={...input,color:input.color||null};if(authenticated){await apiFetch(`planner/requirements${current?`/${current.id}`:""}`,{method:current?"PATCH":"POST",body:JSON.stringify(payload)});return;}if(!current&&requirements.length>=guestLimits.requirements)throw new Error(th?`เพิ่มหมวดหลักสูตรได้สูงสุด ${guestLimits.requirements} รายการ`:`Guest mode supports ${guestLimits.requirements} requirements`);await guestDb.requirements.put({...payload,id:current?.id??crypto.randomUUID(),sort_order:current?.sort_order??requirements.length,actual_credits:0,projected_credits:0});});setRequirementEditor(null);}
  async function deleteRequirement(requirement:Requirement){if(!confirm(th?"ลบหมวดหลักสูตรนี้?":"Delete this requirement?"))return;await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`planner/requirements/${requirement.id}`,{method:"DELETE"});else{await guestDb.requirements.delete(requirement.id);await Promise.all(semesters.map((semester)=>guestDb.semesters.put({...semester,courses:semester.courses.map((course)=>course.requirement_id===requirement.id?{...course,requirement_id:null}:course)})));}});}
  async function assignCourse(course:Course,requirementId:string|null){await mutation.mutateAsync(async()=>{if(authenticated)await apiFetch(`planner/courses/${course.id}/requirement`,{method:"PATCH",body:JSON.stringify({requirement_id:requirementId})});else{const semester=semesters.find((item)=>item.id===course.semester_id);if(semester)await guestDb.semesters.put({...semester,courses:semester.courses.map((item)=>item.id===course.id?{...item,requirement_id:requirementId}:item)});}});}
  const loading=!authReady||(authenticated&&(semestersQuery.isLoading||tasksQuery.isLoading||meetingsQuery.isLoading||requirementsQuery.isLoading))||(!authenticated&&guestQuery.isLoading);
  if(loading)return <div className="space-y-5"><div className="skeleton h-32 rounded-3xl"/><div className="skeleton h-96 rounded-3xl"/></div>;
  return <div className="space-y-6"><header className="card p-6 sm:p-8"><p className="eyebrow">SMART PLANNER</p><div className="mt-2 flex flex-col sm:flex-row gap-4 sm:items-end"><div className="flex-1"><h2 className="text-3xl sm:text-4xl font-black">{th?"งาน ตารางเรียน และหลักสูตร":"Tasks, schedule & degree"}</h2><p className="text-[var(--muted)] mt-2">{th?"จัดการกำหนดส่ง การแจ้งเตือน และความคืบหน้าในที่เดียว":"Manage deadlines, reminders, and degree progress in one place"}</p></div>{tab==="tasks"?<button className="button-primary" disabled={!courses.length} onClick={()=>setTaskEditor("new")}><Plus size={18}/>{th?"เพิ่มงาน":"Add task"}</button>:tab==="schedule"?<button className="button-primary" disabled={!courses.length} onClick={()=>setMeetingEditor(true)}><Plus size={18}/>{th?"เพิ่มเวลาเรียน":"Add class time"}</button>:<button className="button-primary" onClick={()=>setRequirementEditor("new")}><Plus size={18}/>{th?"เพิ่มหมวด":"Add requirement"}</button>}</div></header>
    <nav aria-label="Planner sections" className="card p-2 flex overflow-x-auto">{(["tasks","schedule","requirements"] as Tab[]).map((item)=><button key={item} onClick={()=>setTab(item)} className={`min-w-max flex-1 rounded-xl px-4 py-3 text-sm font-black ${tab===item?"bg-[var(--forest)] text-white":"text-[var(--muted)]"}`}>{item==="tasks"?(th?"งานและกำหนดส่ง":"Tasks & deadlines"):item==="schedule"?(th?"ตารางรายสัปดาห์":"Weekly schedule"):(th?"ความคืบหน้าหลักสูตร":"Degree progress")}</button>)}</nav>
    {message&&<div role="status" className="rounded-2xl border border-[var(--line)] bg-white px-4 py-3 text-sm flex justify-between"><span>{message}</span><button onClick={()=>setMessage("")}>×</button></div>}
    {!courses.length&&tab!=="requirements"?<NoCourses th={th}/>:tab==="tasks"?<TasksPanel tasks={tasks} th={th} locale={locale} busy={mutation.isPending} onEdit={(task)=>setTaskEditor(task)} onToggle={(task)=>void toggleTask(task)} onDelete={(task)=>void deleteTask(task)}/>:tab==="schedule"?<SchedulePanel meetings={meetings} th={th} busy={mutation.isPending} onDelete={(meeting)=>void deleteMeeting(meeting)}/>:<RequirementsPanel requirements={requirements} courses={courses} th={th} busy={mutation.isPending} onEdit={(requirement)=>setRequirementEditor(requirement)} onDelete={(requirement)=>void deleteRequirement(requirement)} onAssign={(course,id)=>void assignCourse(course,id)}/>}
    {taskEditor&&<Modal title={taskEditor==="new"?(th?"เพิ่มงาน":"Add task"):(th?"แก้ไขงาน":"Edit task")} onClose={()=>setTaskEditor(null)}><TaskForm th={th} courses={courses} initial={taskEditor==="new"?undefined:taskEditor} pending={mutation.isPending} onSubmit={(input)=>saveTask(input,taskEditor==="new"?undefined:taskEditor)}/></Modal>}
    {meetingEditor&&<Modal title={th?"เพิ่มเวลาเรียน":"Add class time"} onClose={()=>setMeetingEditor(false)}><MeetingForm th={th} courses={courses} pending={mutation.isPending} onSubmit={saveMeeting}/></Modal>}
    {requirementEditor&&<Modal title={requirementEditor==="new"?(th?"เพิ่มหมวดหลักสูตร":"Add degree requirement"):(th?"แก้ไขหมวดหลักสูตร":"Edit requirement")} onClose={()=>setRequirementEditor(null)}><RequirementForm th={th} initial={requirementEditor==="new"?undefined:requirementEditor} pending={mutation.isPending} onSubmit={(input)=>saveRequirement(input,requirementEditor==="new"?undefined:requirementEditor)}/></Modal>}
  </div>;
}

function TasksPanel({tasks,th,locale,busy,onEdit,onToggle,onDelete}:{tasks:AcademicTask[];th:boolean;locale:string;busy:boolean;onEdit:(task:AcademicTask)=>void;onToggle:(task:AcademicTask)=>void;onDelete:(task:AcademicTask)=>void}){const ordered=[...tasks].sort((a,b)=>Number(a.is_complete)-Number(b.is_complete)||new Date(a.due_at).getTime()-new Date(b.due_at).getTime());return !ordered.length?<Empty icon={CalendarClock} title={th?"ยังไม่มีงาน":"No tasks yet"} text={th?"เพิ่มงานจากรายวิชาเพื่อไม่พลาดกำหนดส่ง":"Add a course task to stay ahead of deadlines"}/>:<section className="space-y-3">{ordered.map((task)=><article key={task.id} className={`card p-4 sm:p-5 flex gap-4 items-start ${task.is_complete?"opacity-60":""}`}><button className={`mt-1 grid h-8 w-8 shrink-0 place-items-center rounded-full border ${task.is_complete?"bg-[var(--forest)] text-white":"border-[var(--line)] bg-white"}`} disabled={busy} onClick={()=>onToggle(task)} aria-label={th?"เปลี่ยนสถานะงาน":"Toggle task"}>{task.is_complete&&<Check size={16}/>}</button><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className={`font-black ${task.is_complete?"line-through":""}`}>{task.title}</h3><span className="rounded-full bg-[#ffebe6] px-2 py-0.5 text-[.68rem] font-black">{typeNames[task.type][th?0:1]}</span></div><p className="text-sm text-[var(--muted)] mt-1">{task.course?.course_code?`${task.course.course_code} · `:""}{task.course?.name}</p><div className="mt-3 flex flex-wrap gap-3 text-xs font-bold"><span className="flex gap-1.5 items-center"><Clock size={14}/>{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(task.due_at))}</span>{task.reminder_offset_minutes!==null&&<span className="flex gap-1.5 items-center"><Bell size={14}/>{reminderLabel(task.reminder_offset_minutes,th)}</span>}</div></div><div className="flex gap-1"><button className="button-secondary !min-h-9 !p-2" onClick={()=>onEdit(task)} aria-label={th?"แก้ไข":"Edit"}><Pencil size={15}/></button><button className="button-danger !min-h-9 !p-2" onClick={()=>onDelete(task)} aria-label={th?"ลบ":"Delete"}><Trash2 size={15}/></button></div></article>)}</section>}

function SchedulePanel({meetings,th,busy,onDelete}:{meetings:Meeting[];th:boolean;busy:boolean;onDelete:(meeting:Meeting)=>void}){return <section className="grid xl:grid-cols-7 gap-3">{weekdays.map((day,index)=>{const items=meetings.filter((meeting)=>meeting.weekday===index+1).sort((a,b)=>a.start_minute-b.start_minute);return <div key={day[1]} className="card min-h-48 p-4"><h3 className="font-black text-sm">{day[th?0:1]}</h3><div className="mt-3 space-y-2">{items.map((meeting)=><article key={meeting.id} className="rounded-xl border-l-4 border-[var(--coral)] bg-[#fff8f4] p-3"><b className="text-xs">{meeting.course.course_code??meeting.course.name}</b><p className="text-xs mt-1">{formatMinute(meeting.start_minute)}–{formatMinute(meeting.end_minute)}</p>{meeting.location&&<p className="text-[.68rem] text-[var(--muted)] mt-1 flex gap-1"><MapPin size={11}/>{meeting.location}</p>}<button className="mt-2 text-[.68rem] font-bold text-red-700" disabled={busy} onClick={()=>onDelete(meeting)}>{th?"ลบ":"Delete"}</button></article>)}{!items.length&&<p className="text-xs text-[var(--muted)]">—</p>}</div></div>})}</section>}

function RequirementsPanel({requirements,courses,th,busy,onEdit,onDelete,onAssign}:{requirements:Requirement[];courses:Course[];th:boolean;busy:boolean;onEdit:(requirement:Requirement)=>void;onDelete:(requirement:Requirement)=>void;onAssign:(course:Course,id:string|null)=>void}){return <div className="space-y-5">{!requirements.length?<Empty icon={GraduationCap} title={th?"ยังไม่มีหมวดหลักสูตร":"No degree requirements"} text={th?"สร้างหมวดหน่วยกิต เช่น วิชาเอกบังคับ หรือวิชาเลือกเสรี":"Create credit groups such as major requirements or free electives"}/>:<section className="grid lg:grid-cols-2 gap-4">{requirements.map((requirement)=>{const actual=Math.min(100,requirement.actual_credits/requirement.required_credits*100);const projected=Math.min(100,requirement.projected_credits/requirement.required_credits*100);return <article key={requirement.id} className="card p-5"><div className="flex gap-3"><span className="h-10 w-2 rounded-full" style={{background:requirement.color??"#123c34"}}/><div className="flex-1"><h3 className="font-black">{requirement.name}</h3><p className="text-sm text-[var(--muted)] mt-1">{requirement.actual_credits} / {requirement.required_credits} {th?"หน่วยกิตจริง":"actual credits"}</p></div><button className="button-secondary !min-h-9 !p-2" onClick={()=>onEdit(requirement)}><Pencil size={15}/></button><button className="button-danger !min-h-9 !p-2" onClick={()=>onDelete(requirement)}><Trash2 size={15}/></button></div><div className="mt-5 relative h-3 rounded-full bg-[#e7ebe5] overflow-hidden"><div className="absolute inset-y-0 left-0 rounded-full opacity-30" style={{width:`${projected}%`,background:requirement.color??"#123c34"}}/><div className="absolute inset-y-0 left-0 rounded-full" style={{width:`${actual}%`,background:requirement.color??"#123c34"}}/></div><p className="mt-2 text-xs text-[var(--muted)]">{th?"รวมแผน":"With planned"}: {requirement.projected_credits} / {requirement.required_credits}</p></article>})}</section>}<section className="card p-5 sm:p-6"><p className="eyebrow">COURSE MAPPING</p><h3 className="font-black text-xl mt-1">{th?"จัดวิชาเข้าหมวดหลักสูตร":"Assign courses to requirements"}</h3><div className="mt-5 divide-y divide-[var(--line)]">{courses.map((course)=><label key={course.id} className="py-3 grid sm:grid-cols-[1fr_15rem] gap-2 items-center"><span className="text-sm font-bold">{course.course_code&&`${course.course_code} · `}{course.name}</span><select className="field !min-h-10" disabled={busy} value={course.requirement_id??""} onChange={(event)=>onAssign(course,event.target.value||null)}><option value="">{th?"ยังไม่จัดหมวด":"Unassigned"}</option>{requirements.map((requirement)=><option key={requirement.id} value={requirement.id}>{requirement.name}</option>)}</select></label>)}</div></section></div>}

function TaskForm({th,courses,initial,pending,onSubmit}:{th:boolean;courses:Course[];initial?:AcademicTask;pending:boolean;onSubmit:(input:TaskInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<TaskInput>({resolver:zodResolver(taskSchema),defaultValues:{title:initial?.title??"",type:initial?.type??"ASSIGNMENT",course_id:initial?.course_id??courses[0]?.id,due_local:initial?toLocalInput(initial.due_at):"",notes:initial?.notes??"",reminder_offset_minutes:initial?.reminder_offset_minutes??1440}});return <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}><label className="block text-sm font-bold">{th?"ชื่องาน":"Task title"}<input className="field mt-2" {...register("title")}/>{errors.title&&<span className="text-xs text-red-700">{errors.title.message}</span>}</label><div className="grid sm:grid-cols-2 gap-4"><label className="block text-sm font-bold">{th?"รายวิชา":"Course"}<select className="field mt-2" {...register("course_id")}>{courses.map((course)=><option key={course.id} value={course.id}>{course.course_code&&`${course.course_code} · `}{course.name}</option>)}</select></label><label className="block text-sm font-bold">{th?"ประเภท":"Type"}<select className="field mt-2" {...register("type")}>{taskTypes.map((type)=><option key={type} value={type}>{typeNames[type][th?0:1]}</option>)}</select></label></div><label className="block text-sm font-bold">{th?"กำหนดส่ง":"Due date & time"}<input type="datetime-local" className="field mt-2" {...register("due_local")}/>{errors.due_local&&<span className="text-xs text-red-700">{errors.due_local.message}</span>}</label><label className="block text-sm font-bold">{th?"แจ้งเตือนล่วงหน้า":"Reminder"}<select className="field mt-2" {...register("reminder_offset_minutes",{valueAsNumber:true})}><option value={-1}>{th?"ไม่แจ้งเตือน":"No reminder"}</option><option value={0}>{th?"เมื่อถึงเวลา":"At due time"}</option><option value={60}>{th?"1 ชั่วโมง":"1 hour"}</option><option value={1440}>{th?"1 วัน":"1 day"}</option><option value={10080}>{th?"1 สัปดาห์":"1 week"}</option></select></label><label className="block text-sm font-bold">{th?"บันทึก":"Notes"}<textarea className="field min-h-24 mt-2" {...register("notes")}/></label><button className="button-primary w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={18}/>:null}{th?"บันทึกงาน":"Save task"}</button></form>}

function MeetingForm({th,courses,pending,onSubmit}:{th:boolean;courses:Course[];pending:boolean;onSubmit:(input:MeetingInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<MeetingInput>({resolver:zodResolver(meetingSchema),defaultValues:{course_id:courses[0]?.id,weekday:1,start_time:"09:00",end_time:"10:30",location:""}});return <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}><label className="block text-sm font-bold">{th?"รายวิชา":"Course"}<select className="field mt-2" {...register("course_id")}>{courses.map((course)=><option key={course.id} value={course.id}>{course.course_code&&`${course.course_code} · `}{course.name}</option>)}</select></label><label className="block text-sm font-bold">{th?"วัน":"Weekday"}<select className="field mt-2" {...register("weekday",{valueAsNumber:true})}>{weekdays.map((day,index)=><option key={day[1]} value={index+1}>{day[th?0:1]}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4"><label className="block text-sm font-bold">{th?"เวลาเริ่ม":"Start"}<input type="time" className="field mt-2" {...register("start_time")}/></label><label className="block text-sm font-bold">{th?"เวลาสิ้นสุด":"End"}<input type="time" className="field mt-2" {...register("end_time")}/>{errors.end_time&&<span className="text-xs text-red-700">{errors.end_time.message}</span>}</label></div><label className="block text-sm font-bold">{th?"สถานที่":"Location"}<input className="field mt-2" {...register("location")}/></label><button className="button-primary w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={18}/>:null}{th?"บันทึกเวลาเรียน":"Save class time"}</button></form>}

function RequirementForm({th,initial,pending,onSubmit}:{th:boolean;initial?:Requirement;pending:boolean;onSubmit:(input:RequirementInput)=>Promise<void>}){const {register,handleSubmit,formState:{errors}}=useForm<RequirementInput>({resolver:zodResolver(requirementSchema),defaultValues:{name:initial?.name??"",required_credits:initial?.required_credits??30,color:initial?.color??"#123c34"}});return <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}><label className="block text-sm font-bold">{th?"ชื่อหมวด":"Requirement name"}<input className="field mt-2" {...register("name")}/>{errors.name&&<span className="text-xs text-red-700">{errors.name.message}</span>}</label><div className="grid grid-cols-[1fr_7rem] gap-4"><label className="block text-sm font-bold">{th?"หน่วยกิตที่ต้องเรียน":"Required credits"}<input type="number" className="field mt-2" {...register("required_credits",{valueAsNumber:true})}/></label><label className="block text-sm font-bold">{th?"สี":"Color"}<input type="color" className="field mt-2 !p-1" {...register("color")}/></label></div><button className="button-primary w-full" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={18}/>:null}{th?"บันทึกหมวด":"Save requirement"}</button></form>}

function NoCourses({th}:{th:boolean}){return <section className="card p-8 text-center"><BookMarked className="mx-auto"/><h3 className="font-black text-xl mt-4">{th?"เพิ่มรายวิชาก่อนใช้แพลนเนอร์":"Add a course before using the planner"}</h3><a className="button-primary mt-5" href={th?"/th/academics":"/en/academics"}>{th?"ไปหน้าการเรียน":"Open academics"}<ChevronRight size={17}/></a></section>}
function Empty({icon:Icon,title,text}:{icon:typeof CalendarClock;title:string;text:string}){return <section className="card min-h-64 grid place-items-center p-8 text-center"><div><Icon className="mx-auto" size={34}/><h3 className="font-black text-xl mt-4">{title}</h3><p className="text-[var(--muted)] mt-2">{text}</p></div></section>}
